language: cpp
compiler:
  - gcc
sudo: false
dist: xenial
addons:
  apt:
    packages:
    - cmake
    - libqt4-dev
script:
  - ./ci/cpplint.sh
  - mkdir ./build
  - cd ./build
  - cmake ../
  - make -j2
  - ctest -V
notifications:
  email: false
